# Generated by Django 3.0.6 on 2020-12-23 20:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='file_src',
            field=models.CharField(choices=[('MOB', 'MOBILE'), ('WAT', 'WATCH')], default='WATCH', max_length=3),
        ),
        migrations.AddField(
            model_name='myfile',
            name='has_sent_to_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), unique=True, upload_to=''),
        ),
    ]
