# Generated by Django 3.0.6 on 2020-12-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201224_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file_src',
            field=models.CharField(choices=[('MOB', 'MOBILE'), ('WAT', 'WATCH')], default='WAT', max_length=3),
        ),
    ]
