# Generated by Django 3.0.6 on 2020-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201224_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='file_src',
            field=models.CharField(choices=[('MOBILE', 'MOBILE'), ('WATCH', 'WATCH')], default='WATCH', max_length=6),
        ),
    ]
