# Generated by Django 3.0.6 on 2020-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20201224_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchDistributionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('phone', models.CharField(help_text='Mobile no of user', max_length=20)),
                ('watch_id', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
