# Generated by Django 3.0.6 on 2020-12-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_watchdistributionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchdistributionmodel',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
