# Generated by Django 3.0.6 on 2021-06-03 19:47

from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20201228_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchdistributionmodel',
            name='registration_id',
            field=models.CharField(default=user_profile.models.get_uuid, editable=False, max_length=36, unique=True),
        ),
        migrations.CreateModel(
            name='UserHealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.WatchDistributionModel')),
            ],
        ),
    ]
