# Generated by Django 3.0.6 on 2021-06-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210604_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhealthprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
