# Generated by Django 3.0.6 on 2021-07-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20210604_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhealthprofile',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='userhealthprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_covid',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_eating_outside',
            field=models.CharField(blank=True, choices=[('Frequently', 'Frequently'), ('Sometimes', 'Sometimes'), ('Never', 'Never'), ('', '')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_heart_disease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_hyper_tension',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_parent_heart_disease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='has_smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('', '')], max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='userhealthprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
