# Generated by Django 3.0.6 on 2021-07-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20210703_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfile',
            name='unix_timestamp_string',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_covid',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_eating_outside',
            field=models.CharField(blank=True, choices=[('Frequently', 'Frequently'), ('Sometimes', 'Sometimes'), ('Never', 'Never')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_heart_disease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_hyper_tension',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_parent_heart_disease',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='userhealthprofile',
            name='has_smoking',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=7, null=True),
        ),
    ]
